#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from server.app.api.models import EvalRubricSubmitRequest, EvalRunAPIRequest, IngestTextRequest, ReplayRequest
from server.app.api.responses import (
    EvalResultsResponse,
    EvalRubricEntriesResponse,
    EvalRubricResponse,
    EvalRunLaunchResponse,
    HealthResponse,
    IngestTextResponse,
    ReplayTraceResponse,
    TracesListResponse,
)
from server.app.core import export_contract_schemas


API_MODELS = {
    "health_response": HealthResponse,
    "ingest_text_response": IngestTextResponse,
    "traces_list_response": TracesListResponse,
    "replay_trace_response": ReplayTraceResponse,
    "eval_run_api_request": EvalRunAPIRequest,
    "eval_run_launch_response": EvalRunLaunchResponse,
    "eval_results_response": EvalResultsResponse,
    "eval_rubric_submit_request": EvalRubricSubmitRequest,
    "eval_rubric_response": EvalRubricResponse,
    "eval_rubric_entries_response": EvalRubricEntriesResponse,
    "ingest_text_request": IngestTextRequest,
    "replay_request": ReplayRequest,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync backend contracts into frontend-generated artifacts.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated artifacts are out of date.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = REPO_ROOT
    target = repo_root / "web" / "lib" / "generated" / "contracts.js"
    expected = render_contract_module()
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != expected:
            raise SystemExit("frontend contract artifacts are out of date; run python3 scripts/sync_web_contracts.py")
        print("web_contracts_check_ok")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8")
    print(f"web_contracts_sync_ok target={target}")


def render_contract_module() -> str:
    payload = export_contract_schemas()
    payload.update({name: model_schema(model) for name, model in API_MODELS.items()})
    rendered = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/sync_web_contracts.py. Do not edit by hand.\n"
        f"export const apiContracts = {rendered};\n"
    )


def model_schema(model: type) -> dict:
    if hasattr(model, "model_json_schema"):
        return model.model_json_schema()
    return model.schema()


if __name__ == "__main__":
    main()
