from __future__ import annotations

from typing import Protocol

from server.app.core import (
    ChunkRecord,
    DocVersionRecord,
    DocumentRecord,
    EvalRunResult,
    GoldenCase,
    JobRecord,
    JobStatus,
    TraceRecord,
)


class DocumentRepository(Protocol):
    def init_schema(self) -> None: ...

    def upsert_document(self, document: DocumentRecord) -> None: ...

    def insert_doc_version(self, doc_version: DocVersionRecord) -> None: ...

    def insert_chunk(self, chunk: ChunkRecord) -> None: ...

    def get_chunk(self, chunk_id: str) -> ChunkRecord | None: ...

    def update_chunk_safe_summary(self, chunk_id: str, safe_summary: str) -> None: ...

    def list_chunks(self) -> list[ChunkRecord]: ...

    def list_chunks_for_doc_version(self, doc_version_id: str) -> list[ChunkRecord]: ...

    def structured_filter_chunks(self, filters: dict[str, object], limit: int | None = None) -> list[ChunkRecord]: ...

    def bm25_search(self, query_text: str, limit: int, filters: dict[str, object] | None = None) -> list[ChunkRecord]: ...


class GoldenCaseRepository(Protocol):
    def upsert_golden_case(self, case: GoldenCase) -> None: ...

    def list_golden_cases(self) -> list[GoldenCase]: ...

    def record_eval_run(self, result: EvalRunResult) -> None: ...

    def list_eval_runs(self) -> list[EvalRunResult]: ...


class FileStore(Protocol):
    def write_markdown_snapshot(self, doc_id: str, doc_version_id: str, raw_text: str) -> str: ...

    def read_markdown_snapshot(self, snapshot_ref: str) -> str: ...


class TraceStore(Protocol):
    def write_trace(self, trace: TraceRecord) -> str: ...

    def read_trace(self, trace_id: str) -> TraceRecord: ...

    def list_trace_ids(self) -> list[str]: ...


class JobRepository(Protocol):
    def enqueue_job(self, job: JobRecord) -> None: ...

    def get_job(self, job_id: str) -> JobRecord | None: ...

    def list_jobs(self, status: JobStatus | None = None, limit: int | None = None) -> list[JobRecord]: ...

    def claim_next_job(self, job_types: list[str] | None = None) -> JobRecord | None: ...

    def update_job_status(
        self,
        job_id: str,
        status: JobStatus,
        error_message: str | None = None,
    ) -> JobRecord | None: ...


class VectorStore(Protocol):
    def ensure_collection(self) -> None: ...

    def upsert_embeddings(self, records: list["EmbeddingUpsertRecord"]) -> None: ...

    def delete_doc_version(self, doc_version_id: str) -> None: ...

    def query(self, query_vector: list[float], top_k: int, where: dict[str, str] | None = None) -> list["VectorQueryMatch"]: ...
